openapi: 3.0.0
info:
  title: API сервер для проекта «Шесть городов».
  description: |-
    * Список ресурсов и маршрутов сервера «Шесть городов».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
tags:
  - name: offers
    description: Действия с объявлениями.
  - name: comments
    description: Действия с комментариями.
  - name: users
    description: Действия с пользователем.
paths:
  /register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя.
      requestBody:
        required: true
        description: Информация для создания нового пользователя.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/registerUser'        
      responses:
        "201":
          description: Пользователь зарегистрирован. Объект пользователя.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "409":
          description: Пользователь с таким email уже существует.
  /login:
    post:
      tags:
        - users
      summary: Авторизация пользователя
      description: Авторизует пользователя на основе логина и пароля
      requestBody:
        required: true
        description: Данные для авторизации пользователя
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: john@example.com
                password:
                  type: string
                  example: password
      responses:
        "200":
          description: Успешная авторизация. Возвращает токен доступа.
          content:
            application/json:
              schema:
                type: string
                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        "401":
          description: Ошибка авторизации
    # get:
    #   tags:
    #     - users
    #   summary: Проверка состояния пользователя
    #   description: Возвращает информацию по авторизованному пользователю
  # /users/{userId}/avatar:
  #   post:
  #     tags:
  #       - users
  #     summary: Загрузить изображение аватара
  #     description: Загружает изображение аватара пользователя. Изображение
  #       аватара должно быть в формате `png` или `jpg`.
  /offers:
    get:
      tags:
       - offers
      summary: Получение списка предложений
      description: Возвращает список предложений
      responses:
         "200":
          description: Список предложений
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
components:
  schemas:
    registerUser:
      type: object
      properties:
        email:
          type: string
          example: john@example.com
        firstname:
          type: string
          example: John
        lastname:
          type: string
          example: Doe
        password:
          type: string
          example: password
    user:
      type: object
      properties:
        id:
          type: string
          example: 5823c3d6a04ab1061c7936fg
        email:
          type: string
          example: john@example.com