# Пользователи
## Создать нового пользователя

POST http://localhost:6000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "kate.r@test.mail",
  "avatarPath": "kate.png",
  "firstName": "Kate",
  "lastName": "Ross",
  "password": "kate-ross"
}

###
